package tcc.balcao.model.entity;

// Generated 22/10/2011 15:14:54 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Contapagamento generated by hbm2java
 */
@Entity
@Table(name = "contapagamento", schema = "public")
public class Contapagamento implements java.io.Serializable {

	private Long idcontaPagamento;
	private Conta conta;
	private Tipopagamento tipopagamento;
	private double valor;

	public Contapagamento() {
	}

	public Contapagamento(Conta conta, Tipopagamento tipopagamento, double valor) {
		this.conta = conta;
		this.tipopagamento = tipopagamento;
		this.valor = valor;
	}

	@SequenceGenerator(name = "generator", allocationSize=1, sequenceName = "public.conta_pagamento_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "idconta_pagamento", unique = true, nullable = false)
	public Long getIdcontaPagamento() {
		return this.idcontaPagamento;
	}

	public void setIdcontaPagamento(Long idcontaPagamento) {
		this.idcontaPagamento = idcontaPagamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idconta", nullable = false)
	public Conta getConta() {
		return this.conta;
	}

	public void setConta(Conta conta) {
		this.conta = conta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipo_pagamento", nullable = false)
	public Tipopagamento getTipopagamento() {
		return this.tipopagamento;
	}

	public void setTipopagamento(Tipopagamento tipopagamento) {
		this.tipopagamento = tipopagamento;
	}

	@Column(name = "valor", nullable = false, precision = 17, scale = 17)
	public double getValor() {
		return this.valor;
	}

	public void setValor(double valor) {
		this.valor = valor;
	}

}
