package tcc.balcao.model.entity;

// Generated 22/10/2011 15:14:54 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Historicopedidos generated by hbm2java
 */
@Entity
@Table(name = "historicopedidos", schema = "public")
public class Historicopedidos implements java.io.Serializable {

	private long idpedido;
	private Statuspedido statuspedido;
	private Item item;
	private Conta conta;
	private Mesa mesa;
	private int quantidade;
	private Date dtAber;
	private Date dtFech;
	private Date dtInicioProc;
	private Date dtFimProc;
	private double valorUnit;

	public Historicopedidos() {
	}

	public Historicopedidos(long idpedido, Statuspedido statuspedido,
			Item item, Conta conta, Mesa mesa, int quantidade, Date dtAber,
			Date dtInicioProc, Date dtFimProc, double valorUnit) {
		this.idpedido = idpedido;
		this.statuspedido = statuspedido;
		this.item = item;
		this.conta = conta;
		this.mesa = mesa;
		this.quantidade = quantidade;
		this.dtAber = dtAber;
		this.dtInicioProc = dtInicioProc;
		this.dtFimProc = dtFimProc;
		this.valorUnit = valorUnit;
	}

	public Historicopedidos(long idpedido, Statuspedido statuspedido,
			Item item, Conta conta, Mesa mesa, int quantidade, Date dtAber,
			Date dtFech, Date dtInicioProc, Date dtFimProc, double valorUnit) {
		this.idpedido = idpedido;
		this.statuspedido = statuspedido;
		this.item = item;
		this.conta = conta;
		this.mesa = mesa;
		this.quantidade = quantidade;
		this.dtAber = dtAber;
		this.dtFech = dtFech;
		this.dtInicioProc = dtInicioProc;
		this.dtFimProc = dtFimProc;
		this.valorUnit = valorUnit;
	}

	@Id
	@Column(name = "idpedido", unique = true, nullable = false)
	public long getIdpedido() {
		return this.idpedido;
	}

	public void setIdpedido(long idpedido) {
		this.idpedido = idpedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idstatus_pedido", nullable = false)
	public Statuspedido getStatuspedido() {
		return this.statuspedido;
	}

	public void setStatuspedido(Statuspedido statuspedido) {
		this.statuspedido = statuspedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iditem", nullable = false)
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idconta", nullable = false)
	public Conta getConta() {
		return this.conta;
	}

	public void setConta(Conta conta) {
		this.conta = conta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmesa", nullable = false)
	public Mesa getMesa() {
		return this.mesa;
	}

	public void setMesa(Mesa mesa) {
		this.mesa = mesa;
	}

	@Column(name = "quantidade", nullable = false)
	public int getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(int quantidade) {
		this.quantidade = quantidade;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_aber", nullable = false, length = 29)
	public Date getDtAber() {
		return this.dtAber;
	}

	public void setDtAber(Date dtAber) {
		this.dtAber = dtAber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_fech", length = 29)
	public Date getDtFech() {
		return this.dtFech;
	}

	public void setDtFech(Date dtFech) {
		this.dtFech = dtFech;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_inicio_proc", nullable = false, length = 29)
	public Date getDtInicioProc() {
		return this.dtInicioProc;
	}

	public void setDtInicioProc(Date dtInicioProc) {
		this.dtInicioProc = dtInicioProc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_fim_proc", nullable = false, length = 29)
	public Date getDtFimProc() {
		return this.dtFimProc;
	}

	public void setDtFimProc(Date dtFimProc) {
		this.dtFimProc = dtFimProc;
	}

	@Column(name = "valor_unit", nullable = false, precision = 17, scale = 17)
	public double getValorUnit() {
		return this.valorUnit;
	}

	public void setValorUnit(double valorUnit) {
		this.valorUnit = valorUnit;
	}

}
