package tcc.balcao.model.entity;

// Generated 22/10/2011 15:14:54 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.FetchMode;
import org.hibernate.annotations.Fetch;

/**
 * Mesa generated by hbm2java
 */
@Entity
@Table(name = "mesa", schema = "public")
public class Mesa implements java.io.Serializable {

	private Integer idmesa;
	private Statusmesa statusmesa;
	private Conta conta;
	private String mesa;
	private Set<Pedidos> pedidoses = new HashSet<Pedidos>(0);
	private Set<Historicopedidos> historicopedidoses = new HashSet<Historicopedidos>(
			0);

	public Mesa() {
	}

	public Mesa(String mesa) {
		this.mesa = mesa;
	}

	public Mesa(Statusmesa statusmesa, Conta conta, String mesa,
			Set<Pedidos> pedidoses, Set<Historicopedidos> historicopedidoses) {
		this.statusmesa = statusmesa;
		this.conta = conta;
		this.mesa = mesa;
		this.pedidoses = pedidoses;
		this.historicopedidoses = historicopedidoses;
	}

	@SequenceGenerator(name = "generator", allocationSize=1, sequenceName = "public.mesa_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "idmesa", unique = true, nullable = false)
	public Integer getIdmesa() {
		return this.idmesa;
	}

	public void setIdmesa(Integer idmesa) {
		this.idmesa = idmesa;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idstatus_mesa")
	public Statusmesa getStatusmesa() {
		return this.statusmesa;
	}

	public void setStatusmesa(Statusmesa statusmesa) {
		this.statusmesa = statusmesa;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idconta")
	public Conta getConta() {
		return this.conta;
	}

	public void setConta(Conta conta) {
		this.conta = conta;
	}

	@Column(name = "mesa", nullable = false, length = 60)
	public String getMesa() {
		return this.mesa;
	}

	public void setMesa(String mesa) {
		this.mesa = mesa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mesa")
	public Set<Pedidos> getPedidoses() {
		return this.pedidoses;
	}

	public void setPedidoses(Set<Pedidos> pedidoses) {
		this.pedidoses = pedidoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mesa")
	public Set<Historicopedidos> getHistoricopedidoses() {
		return this.historicopedidoses;
	}

	public void setHistoricopedidoses(Set<Historicopedidos> historicopedidoses) {
		this.historicopedidoses = historicopedidoses;
	}

}
