package tcc.balcao.model.entity;

// Generated 22/10/2011 15:14:54 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Tipopagamento generated by hbm2java
 */
@Entity
@Table(name = "tipopagamento", schema = "public")
public class Tipopagamento implements java.io.Serializable {

	private Integer idtipoPagamento;
	private String tipo;
	private Set<Contapagamento> contapagamentos = new HashSet<Contapagamento>(0);

	public Tipopagamento() {
	}

	public Tipopagamento(String tipo) {
		this.tipo = tipo;
	}

	public Tipopagamento(String tipo, Set<Contapagamento> contapagamentos) {
		this.tipo = tipo;
		this.contapagamentos = contapagamentos;
	}

	@SequenceGenerator(name = "generator", allocationSize=1, sequenceName = "public.tipo_pagamento_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "idtipo_pagamento", unique = true, nullable = false)
	public Integer getIdtipoPagamento() {
		return this.idtipoPagamento;
	}

	public void setIdtipoPagamento(Integer idtipoPagamento) {
		this.idtipoPagamento = idtipoPagamento;
	}

	@Column(name = "tipo", nullable = false, length = 60)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipopagamento")
	public Set<Contapagamento> getContapagamentos() {
		return this.contapagamentos;
	}

	public void setContapagamentos(Set<Contapagamento> contapagamentos) {
		this.contapagamentos = contapagamentos;
	}

}
