package tcc.balcao.model.entity;

// Generated 22/10/2011 15:14:54 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Conta generated by hbm2java
 */
@Entity
@Table(name = "conta", schema = "public")
public class Conta implements java.io.Serializable {

	private long idconta;
	private Date dtAber;
	private Date dtFech;
	private Set<Contapagamento> contapagamentos = new HashSet<Contapagamento>(0);
	private Set<Pedidos> pedidoses = new HashSet<Pedidos>(0);
	private Set<Mesa> mesas = new HashSet<Mesa>(0);
	private Set<Historicopedidos> historicopedidoses = new HashSet<Historicopedidos>(
			0);

	public Conta() {
	}

	public Conta(long idconta, Date dtAber) {
		this.idconta = idconta;
		this.dtAber = dtAber;
	}

	public Conta(long idconta, Date dtAber, Date dtFech,
			Set<Contapagamento> contapagamentos, Set<Pedidos> pedidoses,
			Set<Mesa> mesas, Set<Historicopedidos> historicopedidoses) {
		this.idconta = idconta;
		this.dtAber = dtAber;
		this.dtFech = dtFech;
		this.contapagamentos = contapagamentos;
		this.pedidoses = pedidoses;
		this.mesas = mesas;
		this.historicopedidoses = historicopedidoses;
	}

	@Id
	@Column(name = "idconta", unique = true, nullable = false)
	public long getIdconta() {
		return this.idconta;
	}

	public void setIdconta(long idconta) {
		this.idconta = idconta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_aber", nullable = false, length = 29)
	public Date getDtAber() {
		return this.dtAber;
	}

	public void setDtAber(Date dtAber) {
		this.dtAber = dtAber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_fech", length = 29)
	public Date getDtFech() {
		return this.dtFech;
	}

	public void setDtFech(Date dtFech) {
		this.dtFech = dtFech;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "conta")
	public Set<Contapagamento> getContapagamentos() {
		return this.contapagamentos;
	}

	public void setContapagamentos(Set<Contapagamento> contapagamentos) {
		this.contapagamentos = contapagamentos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "conta")
	public Set<Pedidos> getPedidoses() {
		return this.pedidoses;
	}

	public void setPedidoses(Set<Pedidos> pedidoses) {
		this.pedidoses = pedidoses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "conta")
	public Set<Mesa> getMesas() {
		return this.mesas;
	}

	public void setMesas(Set<Mesa> mesas) {
		this.mesas = mesas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conta")
	public Set<Historicopedidos> getHistoricopedidoses() {
		return this.historicopedidoses;
	}

	public void setHistoricopedidoses(Set<Historicopedidos> historicopedidoses) {
		this.historicopedidoses = historicopedidoses;
	}

}
