package tcc.balcao.model.entity;

// Generated 22/10/2011 15:14:54 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Statuspedido generated by hbm2java
 */
@Entity
@Table(name = "statuspedido", schema = "public")
public class Statuspedido implements java.io.Serializable {

	private Integer idstatusPedido;
	private String status;
	private Set<Historicopedidos> historicopedidoses = new HashSet<Historicopedidos>(
			0);
	private Set<Pedidos> pedidoses = new HashSet<Pedidos>(0);

	public Statuspedido() {
	}

	public Statuspedido(String status) {
		this.status = status;
	}

	public Statuspedido(String status,
			Set<Historicopedidos> historicopedidoses, Set<Pedidos> pedidoses) {
		this.status = status;
		this.historicopedidoses = historicopedidoses;
		this.pedidoses = pedidoses;
	}

	@SequenceGenerator(name = "generator", allocationSize=1, sequenceName = "public.status_pedido_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "idstatus_pedido", unique = true, nullable = false)
	public Integer getIdstatusPedido() {
		return this.idstatusPedido;
	}

	public void setIdstatusPedido(Integer idstatusPedido) {
		this.idstatusPedido = idstatusPedido;
	}

	@Column(name = "status", nullable = false, length = 60)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statuspedido")
	public Set<Historicopedidos> getHistoricopedidoses() {
		return this.historicopedidoses;
	}

	public void setHistoricopedidoses(Set<Historicopedidos> historicopedidoses) {
		this.historicopedidoses = historicopedidoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statuspedido")
	public Set<Pedidos> getPedidoses() {
		return this.pedidoses;
	}

	public void setPedidoses(Set<Pedidos> pedidoses) {
		this.pedidoses = pedidoses;
	}

}
